Chore: 안드로이드 CI 스크립트 작성
kakao-tech-campus-2nd-step3/Team23_Android pull request #5
Opened 2024-09-18 10:43 UTC by ksc1008

## ✨ 작업 내용
- 안드로이드 워크플로 생성

작업 내용에 따른 세 가지 워크플로를 생성했습니다.

1. Weekly Dev CI
**매 주차별 브랜치**(Weekly/*)에 PR이 발생할 때 실행됩니다.
자동으로 Lint 및 유닛 테스트를 수행하고, PR 코멘트를 통해 결과를 통보합니다.

2. Dev CI
**Master 및 Develop 브랜치**에 PR이 발생할 때 실행됩니다.
Lint, 유닛 테스트에 더해서 계측 테스트(Instrumented Test)를 수행합니다.
계측 테스트는 안드로이드 가상 기기를 직접 실행하여 진행하는 테스트라 수행 시간이 매우 길고, 실행 중 크래시가 발생하기도 합니다.
이런 이유로, 변경이 잦은 Weekly 브랜치에서는 계측 테스트는 생략하게끔 구성하였습니다.

3. Caching After Merge
PR 과정에서 생성된 캐시는 해당 PR에서만 적용되어 새로운 PR이 생성되면 캐시가 존재해도 캐시미스가 발생하는 현상을 확인했습니다. 
이를 해결하기 위해 PR이 머지된 후 캐싱을 수행하는 워크플로를 따로 생성하였습니다.

## 🔍 참고사항 
- CI 과정에 코틀린 컨벤션 확인이 진행됩니다. 
컨벤션에 맞지 않는 코드는 PR 단계에서 반려될 수 있으니 컨벤션에 유의해서 코드를 작성해주세요!

### 참고하면 좋은 커맨드

1. 코틀린 컨벤션 확인:
```
./gradlew ktlintCheck
```

2. 코틀린 컨벤션에 맞춰 코드 포맷:
```
./gradlew ktlintFormat
```

2024-09-18 14:42 UTC, us4c0d3 requested changes
일부 수정사항 코멘트 남겼습니다! 코틀린 빌드 및 이와 관련된 actions 레퍼런스들에 대해 잘 알지 못해 AVD관련된 부분은 제대로 확인하지 못했습니다😢

의문점 등이 있다면 코멘트로 남겨주시면 최대한 이해하고 설명해드리겠습니다!

추가로 회의가 필요하다고 생각되는 부분이 있다면 슬랙이나 회의때 알려주세요 🙌

2024-09-18 14:42 UTC, us4c0d3 commented on .github/workflows/dev.yml
> +          fail_on_error: true
ScaCap/action-ktlint@master의 [리드미](https://github.com/ScaCap/action-ktlint?tab=readme-ov-file#android-deprecated)를 참고해보시면 `android` 옵션은 현재 사용되지 않는다고 되어있습니다. 해당 리드미의 안내를 따라주세요

2024-09-18 14:42 UTC, us4c0d3 commented on .github/workflows/dev.yml
> +        run: ./gradlew test
이전 단계가 실패하더라도 실행을 시키려고 하는 것이 의도라면 코드의 가독성이 더 높아지도록 github actions 내장함수인 `if: always()`사용을 추천드립니다.

2024-09-18 14:42 UTC, us4c0d3 commented on .github/workflows/dev.yml
> +    steps:
계측 테스트를 진행할 것이라면 좀 더 다양한 api-level을 테스트하면 좋을 것 같습니다.

추가로 strategy의 옵션으로 `fail-fast`가 있는데, 여러 api-level을 병렬로 테스트하다가 그 중 하나에 실패가 발생했을 때 중단할지, 아니면 나머지는 테스트를 지속하는 지를 선택하는 옵션입니다. 기본값은 `false`로, 하나가 실패해도 나머지 테스트는 그대로 지속하는 옵션입니다.

호환성을 신경쓸 것이라면 `fail-fast: true`로 두는 것이 좋을 것이고 빠른 개발 및 개발 편의성을 생각한다면 그대로 두면 될 것 같습니다.

2024-09-18 14:42 UTC, us4c0d3 commented on .github/workflows/dev.yml
> +          files: '**/build/outputs/androidTest-results/connected/*/*.xml'
No newline at end of file 에러가 발생할 수 있습니다. 이 부분은 IntelliJ를 사용한다면 [이 글](https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/)을 참고하여 설정해주세요

2024-09-18 14:42 UTC, us4c0d3 commented on .github/workflows/post_merge_caching.yml
> +
dev.yml을 수정한다면 api-level을 맞추면 될 것 같습니다

2024-09-19 04:56 UTC, ksc1008 commented on .github/workflows/dev.yml
> +        run: ./gradlew test
`if: always()`  옵션을 이용하면 사용자가 워크플로를 취소해도 다음 테스트가 진행되는 차이가 존재합니다.
`'!cancelled()'`를 이용할 수도 있지만 분기의 의미를 더 명확히 하기 위해 지금과 같은 분기문을 작성했습니다.

2024-09-19 05:27 UTC, ksc1008 commented on .github/workflows/dev.yml
> +    steps:
개인 리포지토리에서 테스트 했을 때는 일부 API 버전에서 에뮬레이터 가동 시 크래시 현상이 자주 발생했습니다. 

가장 안정적이었던 api 29만 남겨두었는데, 이 부분은 조금 더 테스트해보고 추후 안정적인 범위 내에서 API 레벨을 더 늘려나가야 할 것 같습니다.

2024-09-19 05:29 UTC, us4c0d3 commented on .github/workflows/dev.yml
> +        run: ./gradlew test
그렇다면 그대로 두는 것이 좋을 것 같습니다! 👍

2024-09-19 06:41 UTC, us4c0d3 requested changes
.editorconfig 부분 newline만 처리해주시면 바로 approve 하겠습니다! 새로운 push가 발생하면 다시 approve를 해야돼서 request changes로 남깁니다

2024-09-19 06:41 UTC, us4c0d3 commented on .editorconfig
> +ktlint_code_style = android_studio
No newline at end of the file 에러입니다!

2024-09-19 06:41 UTC, us4c0d3 commented on .github/workflows/dev.yml
> +    steps:
👍

2024-09-19 06:54 UTC, ksc1008 commented
수정하였습니다. 고생 많으셨습니다!

2024-09-19 06:55 UTC, us4c0d3 approved these changes

2024-09-19 06:56 UTC, merged