Test: Test코드 작성
kakao-tech-campus-2nd-step3/Team23_Android pull request #82
Opened 2024-11-01 11:06 UTC by cleonno3o

## PR
### ✨ 작업 내용
- 그동안 기능구현했던 페이지에 대해 테스트코드 작성했습니다.
- 초대관련 페이지 테스트 코드작성
- 지출상세내역 테스트 코드작성
- 로그인페이지 테스트 코드 작성
### 🔍 참고 사항
- ViewModel에 테스트코드를 작성했습니다. 추후 다른 부분도 작성하겠습니다!
- Dispatchers IO와 Main 모두 DI 적용하기 위해서 annotations을 적용했는데 잘 적용되지 않는 것 같아서 지출상세내역 페이지에 Dispatchers.Main은 적용하지 못했습니다..! 해결방법을 알게되면 적용해보겠습니다
- 초대 페이지의 경우 테스트코드를 작성할 필요성을 잘 모르겠어서 틀만 잡아두었습니다. 이미 초대한 경우에 버튼이 비활성화 되기때문에 다시 누르는 상황이 발생하지 않는다 생각했습니다.

### #️⃣ 연관 이슈(Git Close)
- #71 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-11-01 13:21 UTC, ksc1008 requested changes
테스트 케이스 잘 작성하신 것 같습니다!

IO Dispatcher는 지금 구현하신 대로 주입하시면 될 것 같습니다.
Main Dispatcher는 따로 주입할 필요 없이 `Dispatchers.setMain()`만 호출하면 될 것 같네요.
[참고](https://developer.android.com/kotlin/coroutines/test?hl=ko#setting-main-dispatcher)

DI 관련해서 빌드 오류가 발생하는데, DispatcherModule을 뷰모델과 같은 모듈로 이동하면 될 것 같습니다. 
DI 에러 해결하시면 바로 머저해도 될 것 같습니다.

2024-11-01 13:21 UTC, ksc1008 commented on ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
> +        every { Log.e(any(), any()) } returns 0
P3: 아무 것도 하지 않는 함수를 모킹하고 싶으면, `every { func() } just Runs` 를 사용하는게 더 적절해보여요!

2024-11-01 13:44 UTC, cleonno3o commented on ui/expensedetail/src/test/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailViewModelTest.kt
> +        every { Log.e(any(), any()) } returns 0
just Runs는 리턴값이 없는 함수에만 적용되어서 값을 반환하는 Log 함수에는 사용이 불가한가봐요!

2024-11-01 14:01 UTC, cleonno3o commented
Annotation 추가하고 나서 테스트 에러가 나는 것 같아서 없애서 원래대로 복구해서 일단 해결했습니다! DispatcherModule을 여러 UI의 ViewModel에서 사용하는데 추후 수정하면 어디로 옮겨야 할까요?! common에 dispatcher를 새로 만드는 것이 맞을까요?

2024-11-01 14:06 UTC, ksc1008 commented
> Annotation 추가하고 나서 테스트 에러가 나는 것 같아서 없애서 원래대로 복구해서 일단 해결했습니다! DispatcherModule을 여러 UI의 ViewModel에서 사용하는데 추후 수정하면 어디로 옮겨야 할까요?! common에 dispatcher를 새로 만드는 것이 맞을까요?

common 하위 모듈을 만들거나 아니면 그냥 app 모듈에 두어도 될 것 같아요!

2024-11-01 14:46 UTC, cleonno3o commented
하위 모듈 만들어서 이동했습니다~!

2024-11-01 14:55 UTC, ksc1008 approved these changes, later dismissed
수고하셨습니다!

2024-11-02 10:16 UTC, cleonno3o commented
Weekly10으로 머지해야할것 같아 바꾸었습니다!

2024-11-02 11:14 UTC, ksc1008 approved these changes

2024-11-02 11:50 UTC, merged