Refactor: 리포지토리 구조 변경, Expense 모듈 내 Repository 구현
kakao-tech-campus-2nd-step3/Team23_Android pull request #88
Opened 2024-11-02 08:11 UTC by ksc1008

## 리포지토리 구조 변경, Expense 모듈 내 Repository 구현
### ✨ 작업 내용
- ExpenseRepository 구조 변경
- ExpenseDetailReplositoryImpl 구현
- ExpenseListRepositoryImpl 구현
- AddExpenseActivity에서 그룹 정보를 넘겨 받게 구현
- ExepenseDetailActivity에서 지출 정보를 넘겨 받게 구현

리포지토리 인터페이스를 수정했습니다.
이를 참조하는 UseCase 및 ViewModel 또한 수정하였습니다.

### 수정 전
![before drawio](https://github.com/user-attachments/assets/4f2eb91d-b27e-4f48-8dab-5716f7158491)

### 수정 후
![after drawio](https://github.com/user-attachments/assets/da23f79c-76e0-426e-879f-6aed8748f7a2)

### 🔍 참고 사항
- 몇가지 기능은 미구현 상태입니다. ExpenseDetail 업데이트 같은 경우, 관련 API가 제대로 명시가 되어있지 않아 구현하지 못했습니다.
- ExpenseDetail 액티비티에서 인텐트를 통해 ExpenseID 를 넘겨받는 로직은 구현했지만, 실제로 액티비티를 전환할 때 ExpenseID를 넘겨주는 코드는 아직 작성하지 않았습니다. 

### #️⃣ 연관 이슈(Git Close)
- #79 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-11-03 05:02 UTC, cleonno3o requested changes
수고하셨습니다!! 몇가지 기능은 미구현 하셨다 했지만 일단 생각해 볼만한 점 몇가지 남겨드렸어요!
생각해보시고 맞는 것 같은 방향으로 하시면 될 것 같습니다 테스트는 한번 확인해보시면 될 것 같아요!

2024-11-03 05:02 UTC, cleonno3o commented on ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
> +        }
P3: expenseId 가 null일 경우 0을 지정해서 특정 값을 보내기 보다는 nullable로 보내서 후에 판단하는건 어떨까요?!
```suggestion
    if (expenseId == null) {
        Toast.makeText(this, "지출 정보를 불러오는 데 실패했습니다.", Toast.LENGTH_LONG).show()
    }   
    viewModel.updateExpenseIdAndInit(expenseId)
}
```

2024-11-03 05:02 UTC, cleonno3o commented on data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
> +    }
P3: 여기도 수정한다면 똑같이 할 수 있지 않을까 싶습니다

2024-11-03 05:02 UTC, cleonno3o commented on data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
>      }
P2: 업로드 성공 실패 여부를 UseCase에서 전달하려면 값을 반환해주어야할 것 같아요~ 추가적으로 201 일때와 response.code() /100 == 2 가 수행할 동작이 동일하다면 아래처럼 고쳐도 될 것 같아요
```suggestion
override suspend fun uploadExpense(receiptItem: ReceiptItem, groupId: String): String? {
    return try {
        val jwt = getJwt()
        if (!isJwtValid(jwt)) {
            return null
        }

        val response = dataSource.addExpense(receiptItem, jwt, groupId)
        return when (response.code()) {
            in 200..299 -> response.body()?.expenseId?.let {
                return it
            } ?: throw IllegalStateException("알 수 없는 오류 발생: ${response.message()}")
            400 -> throw IllegalArgumentException("유효하지 않는 입력 값")
            404 -> throw IllegalStateException(response.message())
            500 -> throw IllegalStateException(response.message())
            else -> throw IllegalStateException("알 수 없는 오류 발생: ${response.message()}")
        }
    } catch (e: Exception) {
        e.printStackTrace()
        null
    }
}
```

2024-11-03 05:02 UTC, cleonno3o commented on ui/addexpense/src/main/java/com/kappzzang/jeongsan/addexpense/AddExpenseViewModel.kt
>          return true
P2: uploadExpenseUseCase의 반환값이 유효할때만 true를 반환해야할 것 같아요!

2024-11-03 09:06 UTC, ksc1008 commented on ui/expensedetail/src/main/java/com/kappzzang/jeongsan/expensedetail/ExpenseDetailActivity.kt
> +        }
해당 코드는 지출 정보를 전달하는 로직이 구현이 안 되있어 무조건 실패하는 분기입니다.
더미 데이터 표시를 위해 임시로 코드를 작성해놓았고, 구현이 끝나면 expenseId가 null인 경우 이전 페이지로 돌아가는 등 추가적인 예외 처리를 해야할 것 같습니다.
아직 API 통합이 덜 끝나서 수정 예정인 부분인데, 주석 처리를 안해서 혼란을 빚은것 같네요.

2024-11-03 09:08 UTC, cleonno3o commented on data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
>      }
실패시 이유에 따라 처리할 경우가 있을 수 있겠네요! 거기까지는 생각을 못해봤네요. 좋은 의견 감사합니다!ㅎㅎ 바꾼다면 말씀하신대로 수현님 방식대로 하는 것이 좋을 것 같습니다!

2024-11-03 09:40 UTC, ksc1008 commented on data/expense/src/main/java/com/kappzzang/jeongsan/repositoryimpl/ExpenseListRepositoryImpl.kt
>      }
좋은 의견 감사합니다. 네트워크 에러에 대한 처리가 확실히 미흡한 것 같네요.
저의 경우엔, UseCase에서 try-catch 문을 이용해 에러 처리를 수행하는 방식을 생각했습니다. 
하지만, 수현님의 방식처럼 데이터 레이어 내부에서 에러 핸들링을 끝내고, 성공/실패 여부를 포함한 Result 객체를 리턴하는 방식이 더 적절한 것 같아요.
단순히 실패 시 null을 리턴하여도 좋지만, 나중에 실패 이유에 따라 뷰모델에서 유동적으로 처리를 해야할 수도 있으니 (ex: 인증 오류면 다시 로그인, 네트워크 오류면 재시도, 404면 취소) Result 객체에 실패 이유를 담아서 리턴하는 방식이 좋지 않을까 생각합니다.

2024-11-04 23:55 UTC, ksc1008 commented
구현이 덜 끝난 부분 마저 구현하고, 리턴 타입 `Result<T>`로 통일했습니다!

2024-11-05 02:53 UTC, jsh00325 reviewed
아래에 API 에러처리 관해서 하나 남겨두었습니다!
확인부탁드려요!

2024-11-05 02:53 UTC, jsh00325 commented on data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
> +        }
P2: 이 부분에서 400와 같은 에러 코드에 대해서 오류를 throw하는데, 해당 부분을 `ExpenseDetailRemoteDatasource`와 같이 `Result.failure()`로 감싸는거는 어떨까요?

```kotlin
private fun <T> processResponseCode(response: Response<T>): Result<T> {
    return when (response.code()) {
        400 -> Result.failure(IllegalArgumentException("유효하지 않은 입력 값"))
        404 -> Result.failure(IllegalStateException(response.message()))
        500 -> Result.failure(IllegalStateException(response.message()))
        else -> {
            if (response.code() / 100 == 2) {
                response.body()?.let {
                    Result.success(it)
                } ?: Result.failure(IllegalStateException("알 수 없는 오류 발생: ${response.message()}"))
            } else {
                Result.failure(IllegalStateException("알 수 없는 오류 발생: ${response.message()}"))
            }
        }
    }
}
```

2024-11-05 03:56 UTC, ksc1008 commented on data/expense/src/main/java/com/kappzzang/jeongsan/datasource/ExpenseListRemoteDatasource.kt
> +        }
실수로 고치지 않았네요! 수정하겠습니다.

2024-11-05 04:13 UTC, ksc1008 commented
Test Fail 뜨는데, 변경사항이랑 연관없는 테스트라 무시하고 따로 픽스해야할 것 같습니다.

2024-11-05 04:23 UTC, jsh00325 approved these changes

2024-11-05 04:24 UTC, cleonno3o approved these changes

2024-11-05 05:06 UTC, merged